### ISSUE TITLE
Instructions to build for On-Premise IDOL installation

### ISSUE THREAD

**Issue by budlande** [hpautonomy/find#2]
It looks like the code may be in place to build against a local IDOL installation, do you have any instructions to do so?

**Comment by brian-beckett-hp** [comment]
Hi @budlande.  Yes, the code is in place for using Find against IDOL and Haven OnDemand.  Documentation coming soon!

**Comment by brian-beckett-hp** [comment]
Hi @budlande 

We've added some documentation to the [wiki](https://github.com/hpautonomy/find/wiki) for Find.  The instructions for how to build Find are [here](https://github.com/hpautonomy/find/wiki/Building-Find)

Thanks,

Brian
